files:
  train_data: data/task 1/training_set_task1.json
  dev_data: data/task 1/dev_set_task1.json
  test_data: data/task 1/test_set_task1.json
  
params:
  max_len: 128
  batch_size: 8
  epochs: 15
  learning_rate: 0.000005
